// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth_attempts.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countFailedAuthAttemptsSince = `-- name: CountFailedAuthAttemptsSince :one
SELECT COUNT(*)
FROM auth_attempts
WHERE action = $1
AND email = $2
AND created_at >= $3
AND outcome = 'failed'
`

type CountFailedAuthAttemptsSinceParams struct {
	Action    AuthAction
	Email     string
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) CountFailedAuthAttemptsSince(ctx context.Context, arg CountFailedAuthAttemptsSinceParams) (int64, error) {
	row := q.db.QueryRow(ctx, countFailedAuthAttemptsSince, arg.Action, arg.Email, arg.CreatedAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTieredAuthAttempts = `-- name: CountTieredAuthAttempts :one
SELECT
  COUNT(*) AS old_count,
  COUNT(*) FILTER (WHERE created_at >= ($1)) AS recent_count
FROM auth_attempts
WHERE action = $2
  AND email = $3
  AND created_at >= $4
`

type CountTieredAuthAttemptsParams struct {
	RecentDate pgtype.Timestamptz
	Action     AuthAction
	Email      string
	OldDate    pgtype.Timestamptz
}

type CountTieredAuthAttemptsRow struct {
	OldCount    int64
	RecentCount int64
}

func (q *Queries) CountTieredAuthAttempts(ctx context.Context, arg CountTieredAuthAttemptsParams) (CountTieredAuthAttemptsRow, error) {
	row := q.db.QueryRow(ctx, countTieredAuthAttempts,
		arg.RecentDate,
		arg.Action,
		arg.Email,
		arg.OldDate,
	)
	var i CountTieredAuthAttemptsRow
	err := row.Scan(&i.OldCount, &i.RecentCount)
	return i, err
}

const createLoginAuthAttempt = `-- name: CreateLoginAuthAttempt :exec
INSERT INTO auth_attempts (
  action, email, outcome
) VALUES ( $1, $2, $3 )
`

type CreateLoginAuthAttemptParams struct {
	Action  AuthAction
	Email   string
	Outcome AuthOutcome
}

func (q *Queries) CreateLoginAuthAttempt(ctx context.Context, arg CreateLoginAuthAttemptParams) error {
	_, err := q.db.Exec(ctx, createLoginAuthAttempt, arg.Action, arg.Email, arg.Outcome)
	return err
}
