// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth_attempts.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countFailedAuthAttemptsSince = `-- name: CountFailedAuthAttemptsSince :one
SELECT COUNT(*)
FROM auth_attempts
WHERE action = $1
AND email = $2
AND created_at >= $3
AND outcome = 'failed'
`

type CountFailedAuthAttemptsSinceParams struct {
	Action    AuthAction
	Email     string
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) CountFailedAuthAttemptsSince(ctx context.Context, arg CountFailedAuthAttemptsSinceParams) (int64, error) {
	row := q.db.QueryRow(ctx, countFailedAuthAttemptsSince, arg.Action, arg.Email, arg.CreatedAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createLoginAuthAttempt = `-- name: CreateLoginAuthAttempt :exec
INSERT INTO auth_attempts (
  action, email, outcome
) VALUES ( $1, $2, $3 )
`

type CreateLoginAuthAttemptParams struct {
	Action  AuthAction
	Email   string
	Outcome AuthOutcome
}

func (q *Queries) CreateLoginAuthAttempt(ctx context.Context, arg CreateLoginAuthAttemptParams) error {
	_, err := q.db.Exec(ctx, createLoginAuthAttempt, arg.Action, arg.Email, arg.Outcome)
	return err
}
