// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: password_reset_requests.sql

package db

import (
	"context"
)

const createPasswordResetRequest = `-- name: CreatePasswordResetRequest :one
INSERT INTO password_reset_requests (
  id, user_id
) VALUES ( $1, $2 )
RETURNING id, user_id, created_at
`

type CreatePasswordResetRequestParams struct {
	ID     []byte
	UserID int64
}

func (q *Queries) CreatePasswordResetRequest(ctx context.Context, arg CreatePasswordResetRequestParams) (PasswordResetRequest, error) {
	row := q.db.QueryRow(ctx, createPasswordResetRequest, arg.ID, arg.UserID)
	var i PasswordResetRequest
	err := row.Scan(&i.ID, &i.UserID, &i.CreatedAt)
	return i, err
}

const deletePasswordResetRequestByID = `-- name: DeletePasswordResetRequestByID :exec
DELETE FROM password_reset_requests
WHERE id = $1
`

func (q *Queries) DeletePasswordResetRequestByID(ctx context.Context, id []byte) error {
	_, err := q.db.Exec(ctx, deletePasswordResetRequestByID, id)
	return err
}

const getPasswordResetRequestByID = `-- name: GetPasswordResetRequestByID :one
SELECT id, user_id, created_at
FROM password_reset_requests
WHERE id = $1
`

func (q *Queries) GetPasswordResetRequestByID(ctx context.Context, id []byte) (PasswordResetRequest, error) {
	row := q.db.QueryRow(ctx, getPasswordResetRequestByID, id)
	var i PasswordResetRequest
	err := row.Scan(&i.ID, &i.UserID, &i.CreatedAt)
	return i, err
}
