// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package db

import (
	"context"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (
    id,
    user_id
) VALUES (
    $1,
    $2
)
RETURNING id, user_id, created_at, last_seen_at, last_refreshed_at, is_active
`

type CreateSessionParams struct {
	ID     []byte
	UserID int64
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession, arg.ID, arg.UserID)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.LastRefreshedAt,
		&i.IsActive,
	)
	return i, err
}

const deactivateAllSessionsForUser = `-- name: DeactivateAllSessionsForUser :exec
UPDATE sessions
SET is_active = FALSE
WHERE user_id = $1 AND is_active = TRUE
`

func (q *Queries) DeactivateAllSessionsForUser(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, deactivateAllSessionsForUser, userID)
	return err
}

const deactivateLeastRecentlyUsedSessionForUser = `-- name: DeactivateLeastRecentlyUsedSessionForUser :exec
UPDATE sessions
SET is_active = FALSE
WHERE id = (
  SELECT s.id
  FROM sessions s
  WHERE s.user_id = $1 and is_active = TRUE
  ORDER BY s.last_seen_at ASC
  LIMIT 1
)
`

func (q *Queries) DeactivateLeastRecentlyUsedSessionForUser(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, deactivateLeastRecentlyUsedSessionForUser, userID)
	return err
}

const deactivateSession = `-- name: DeactivateSession :exec
UPDATE sessions
SET is_active = FALSE
WHERE id = $1 and is_active = TRUE
`

func (q *Queries) DeactivateSession(ctx context.Context, id []byte) error {
	_, err := q.db.Exec(ctx, deactivateSession, id)
	return err
}

const getActiveSession = `-- name: GetActiveSession :one
SELECT s.id, s.user_id, s.created_at, s.last_seen_at, s.last_refreshed_at, s.is_active
FROM sessions s
JOIN users u on s.user_id = u.id 
WHERE s.id = $1 AND s.is_active = TRUE and u.is_active = TRUE
`

func (q *Queries) GetActiveSession(ctx context.Context, id []byte) (Session, error) {
	row := q.db.QueryRow(ctx, getActiveSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.LastRefreshedAt,
		&i.IsActive,
	)
	return i, err
}

const getSessionCountByUser = `-- name: GetSessionCountByUser :one
SELECT COUNT(*)
FROM sessions
WHERE user_id = $1 and is_active = TRUE
`

func (q *Queries) GetSessionCountByUser(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, getSessionCountByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const updateSessionIDAndRefreshedAt = `-- name: UpdateSessionIDAndRefreshedAt :one
UPDATE sessions
SET id = $2, last_refreshed_at = NOW()
WHERE id = $1 and is_active = TRUE
RETURNING id, user_id, created_at, last_seen_at, last_refreshed_at, is_active
`

type UpdateSessionIDAndRefreshedAtParams struct {
	ID   []byte
	ID_2 []byte
}

func (q *Queries) UpdateSessionIDAndRefreshedAt(ctx context.Context, arg UpdateSessionIDAndRefreshedAtParams) (Session, error) {
	row := q.db.QueryRow(ctx, updateSessionIDAndRefreshedAt, arg.ID, arg.ID_2)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.LastRefreshedAt,
		&i.IsActive,
	)
	return i, err
}

const updateSessionLastSeenToNow = `-- name: UpdateSessionLastSeenToNow :one
UPDATE sessions
SET last_seen_at = NOW()
WHERE id = $1 and is_active = TRUE
RETURNING id, user_id, created_at, last_seen_at, last_refreshed_at, is_active
`

func (q *Queries) UpdateSessionLastSeenToNow(ctx context.Context, id []byte) (Session, error) {
	row := q.db.QueryRow(ctx, updateSessionLastSeenToNow, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.LastRefreshedAt,
		&i.IsActive,
	)
	return i, err
}
